project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd

website:
  title: "Météo"
  page-navigation: true
  repo-url: https://github.com/guibouland/ProjetGroupe
  repo-actions: [source, issue]
  
  navbar:
    tools: 
      - icon: github
        href: https://github.com/guibouland/ProjetGroupe
        text: GitHub
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: En savoir plus
      

        
execute:
  echo: false          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
jupyter: python3

