project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - more.qmd

website:
  title: "Météo"
  page-navigation: true
  repo-url: https://github.com/guibouland/ProjetGroupe
  repo-actions: [source, issue]
  
  navbar:
    tools: 
      - icon: github
        href: https://github.com/guibouland/ProjetGroupe
        text: GitHub
    left:
      - href: index.qmd
        text: Home
      - href: more.qmd
        text: More
      - href: about.qmd
        text: About
      

        
output:
  html:
    media:
      display: true           


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
jupyter: python3
editor: visual

